"""Generate the analytic helix-transport Jacobian for transportJacobianBxByBzD.

Output: 5 x 9 Jacobian
  parms_out  = (qop, lam, phi, xt, yt)
  parms_in   = (qop0, lam0, phi0, xt0, yt0, Bx, By, Bz, xi)

The Bx, By, Bz columns are the partials with respect to the field components
that drive the trajectory, in whatever units B is supplied (the CMSSW caller
supplies field in 1/GeV via theField->inInverseGeV; the post-multiply
res.middleCols(5,3) *= kTeslaToInvGeV converts the columns to per-Tesla so the
chain-rule callers can multiply by Tesla-valued field offsets / basis values).

Run inside the wmassdev container (sympy 1.14):

  APPTAINER_BIND="/tmp,/home/submit,/work/submit,/scratch/submit,/ceph/submit,\
/cvmfs,/etc/grid-security,/run" \
    singularity run --nv \
    /cvmfs/unpacked.cern.ch/gitlab-registry.cern.ch/bendavid/cmswmassdocker/\
wmassdevrolling:v48_patch0 \
    python3 TrackPropagation/Geant4e/python/gen_transport_jacobian.py \
    > /tmp/transport_jacobian_body.cxx

The hand-written setup (Bx/By/Bz from bfield+dB, M0x/y/z, W0, qop0 = q/|p|) is
NOT regenerated by this script -- only the CSE block, the derivative block and
the Eigen result block are emitted.

Pinned: SymPy 1.14.0. Provenance: derived from Bendavid scipy-MuCal commit
3567123a (branch obsopt), with Bx and By added to inparms. Validated via
TrackPropagation/Geant4e/test/transport_jacobian_fd.py (machine-precision dBz
column equivalence with the previous 5x7 generator; 1e-7 FD closure on the new
dBx/dBy partial columns).
"""
import sympy
from sympy.printing.cxx import cxxcode
from sympy.vector import CoordSys3D


coords = CoordSys3D("coords")

M0x, M0y, M0z = sympy.symbols("M0x M0y M0z")
M0const = M0x*coords.i + M0y*coords.j + M0z*coords.k

qop0 = sympy.Symbol("qop0", nonzero=True)
lam0 = sympy.Symbol("lam0")
phi0 = sympy.Symbol("phi0")
xt0 = sympy.Symbol("xt0")
yt0 = sympy.Symbol("yt0")
q = sympy.Symbol("q")
mass = sympy.Symbol("mass")

p0 = q/qop0
dEdx = sympy.Symbol("dEdx")
xi = sympy.Symbol("xi")

W0x, W0y, W0z = sympy.symbols("W0x W0y W0z")
W0 = W0x*coords.i + W0y*coords.j + W0z*coords.k
U0 = coords.k.cross(W0).normalize()
V0 = W0.cross(U0)

Bx = sympy.Symbol("Bx")
By = sympy.Symbol("By")
Bz = sympy.Symbol("Bz")
Bv = Bx*coords.i + By*coords.j + Bz*coords.k
H = Bv.normalize()
B = Bv.magnitude()

s = sympy.Symbol("s")

qop0val = sympy.Symbol("qop0val")
lam0val = sympy.atan(W0z/sympy.sqrt(W0x**2 + W0y**2))
phi0val = sympy.atan2(W0y, W0x)
xt0val = M0const.dot(U0)
yt0val = M0const.dot(V0)
zt0val = M0const.dot(W0)
Bzval = sympy.Symbol("Bzval")
sval = sympy.Symbol("sval")

subsconst = [(qop0, qop0val), (lam0, lam0val), (phi0, phi0val),
             (xt0, xt0val), (yt0, yt0val), (Bz, Bzval), (s, sval), (xi, 0)]
subsrev = [(qop0val, qop0), (Bzval, Bz), (sval, s), (xi, 0)]

M0 = xt0*U0 + yt0*V0 + zt0val*W0
T0 = (sympy.cos(lam0)*sympy.cos(phi0)*coords.i
      + sympy.cos(lam0)*sympy.sin(phi0)*coords.j
      + sympy.sin(lam0)*coords.k)

HcrossT0 = H.cross(T0)
N0 = HcrossT0.normalize()
alpha = HcrossT0.magnitude()
gamma = H.dot(T0)

Q = -B*qop0
theta = Q*s
costheta = sympy.cos(theta)
sintheta = sympy.sin(theta)

print("// generating M, T (this takes ~30s)", flush=True)
M = M0 + gamma*(theta-sintheta)/Q*H + sintheta/Q*T0 + alpha*(1-costheta)/Q*N0
M = M.simplify()
T = 1*sympy.diff(M, s).simplify()

W = T.subs(subsconst).simplify()
U = coords.k.cross(W).normalize()
V = W.cross(U)

tx = T.dot(coords.i)
ty = T.dot(coords.j)
tz = T.dot(coords.k)
tt = sympy.sqrt(tx**2 + ty**2)

xifact = sympy.exp(xi)
energy0 = sympy.sqrt(p0*p0 + mass*mass)
energy = energy0 + xifact*dEdx*s
qop = q/sympy.sqrt(energy*energy - mass*mass)

lam = sympy.atan(tz/tt)
phi = sympy.atan2(ty, tx)
xt = M.dot(U)
yt = M.dot(V)

parms = [qop, lam, phi, xt, yt]
parmlabels = ["qop", "lam", "phi", "xt", "yt"]

# Bx, By added relative to the original Bz-only generator.
inparms = [qop0, lam0, phi0, xt0, yt0, Bx, By, Bz, xi]
inparmlabels = ["qop0", "lam0", "phi0", "xt0", "yt0", "Bx", "By", "Bz", "xi"]

print("// computing ds/dinparms", flush=True)
dsdinparms = []
for inparm in inparms:
    dsdinparm = -1*T.dot(sympy.diff(M, inparm))
    dsdinparm = dsdinparm.subs(subsconst).subs(subsrev)
    dsdinparms.append(dsdinparm)

print("// computing chain-rule derivatives", flush=True)
results = []
labels = []
for parm, parmlabel in zip(parms, parmlabels):
    dparmds = 1*sympy.diff(parm, s)
    dparmds = dparmds.subs(subsconst).subs(subsrev)
    for inparm, inparmlabel, dsdinparm in zip(inparms, inparmlabels, dsdinparms):
        dparmdinparm = 1*sympy.diff(parm, inparm)
        dparmdinparm = dparmdinparm.subs(subsconst).subs(subsrev)
        res = dparmdinparm + dparmds*dsdinparm
        res = 1*res
        labels.append(f"d{parmlabel}d{inparmlabel}")
        results.append(res)

print("// CSE-ing", flush=True)
substitutions, results2 = sympy.cse(results)

# Emit C++. The caller is expected to wrap this body inside the
# transportJacobianBxByBzD function definition; symbol names match the
# hand-written setup block (M0x/y/z, W0x/y/z, q, qop0, mass, dEdx, s, Bx, By,
# Bz, xi).
for sub in substitutions:
    cxxsub = cxxcode(sub[1], standard='C++17')
    print(f"  const double {sub[0]} = {cxxsub};")
for res, label in zip(results2, labels):
    cxxres = cxxcode(res, standard='C++17')
    print(f"  const double {label} = {cxxres};")

print(f"  Eigen::Matrix<double, {len(parms)}, {len(inparms)}> res;")
for i, parmlabel in enumerate(parmlabels):
    for j, inparmlabel in enumerate(inparmlabels):
        print(f"  res({i},{j}) = d{parmlabel}d{inparmlabel};")
