#!/usr/bin/env python3
"""Regenerate geometry + planes + watcher radii TOGETHER for a given layer T.

These three must agree or the test is silently wrong: the geometry sets where
the boundaries are, toyPlanes sets where the model propagates, and the watcher
radii set what the sim records. Generating them from one place is the only way
to keep them consistent when T changes.

Radius 27.1 is dropped: it sits 0.2 cm from 26.9 (a stereo-pair partner) and
would overlap for any layer thicker than that. 14 scoring surfaces remain.

rho ~ 1/T keeps rho*T fixed, so the INTEGRATED material is nominally constant
and only the layer/step structure changes. Nominally: the Sternheimer density
effect still shifts dE by a few % over a large rho range (measured 7 % over 6x),
so quote the dE that comes out rather than assuming it is fixed.

Second argument NSUB subdivides each layer into NSUB sub-shells of the SAME
material. That is the clean way to vary step structure: rho, total material,
radial material distribution and scoring surfaces all stay identical, and only
the number of forced boundaries changes (2 per station -> NSUB+1). Sub-shells of
identical material still terminate Geant4 steps, which is what the whole design
relies on. Contrast with scaling rho ~ 1/T, which drifts dE by ~11 % through the
Sternheimer density effect and so does NOT hold the material fixed.

usage: python gen_toy_config.py T_cm [NSUB]
"""
import math
import os
import sys

# "homo" builds the ORIGINAL homogeneous toy: one uniform medium filling the
# whole tracking volume, sliced ONLY at the scoring radii. Those slices are pure
# bookkeeping (identical material either side) so they add no physics, but they
# also add almost no step truncation -- gaps between scoring radii run to ~16 cm,
# far beyond the propagator's 10 mm ceiling. That is precisely why this geometry
# leaves the step limit fully exposed and is the right place to scan it.
HOMO = sys.argv[1] == "homo"
if HOMO:
    T, NSUB = 0.0, 1
else:
    T = float(sys.argv[1])
    NSUB = int(sys.argv[2]) if len(sys.argv) > 2 else 1
# rho FIXED: the material must be genuinely identical across the scan, not just
# nominally. Only NSUB varies the boundary count.
# layered: rho fixed at 9.0 so only NSUB varies. homogeneous: 0.1073, which
# reproduces the real tracker's MEAN loss (24.99 MeV) over the same z-extent.
RHO = float(sys.argv[2]) if (len(sys.argv) > 2 and sys.argv[1] == "homo") else 9.0
RADII = [4.2, 7.3, 10.2, 26.9, 35.2, 40.3, 43.2, 51.8, 61.6, 67.9, 75.0,
         85.5, 94.6, 106.8]
RMIN, RMAX, DZ = 3.15, 123.0, 194.0
gaps = [RADII[i + 1] - RADII[i] for i in range(len(RADII) - 1)]
if not HOMO and T >= min(gaps):
    raise SystemExit(f"T={T} too large: smallest radius gap is {min(gaps)} cm")

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(os.path.dirname(HERE), "data")

# ---- geometry
sol, lp, pos = [], [], []
def add(name, r0, r1, mat):
    sol.append(f'  <Tubs name="{name}" rMin="{r0:.4f}*cm" rMax="{r1:.4f}*cm" '
               f'dz="{DZ}*cm" startPhi="0*deg" deltaPhi="360*deg"/>')
    lp.append(f'  <LogicalPart name="{name}" category="unspecified">\n'
              f'   <rSolid name="tracker:{name}"/>\n   <rMaterial name="{mat}"/>\n'
              f'  </LogicalPart>')
    pos.append(f'  <PosPart copyNumber="1">\n   <rParent name="tracker:Tracker"/>\n'
               f'   <rChild name="tracker:{name}"/>\n  </PosPart>')

if HOMO:
    # contiguous shells of the SAME material; the only boundaries are the
    # scoring surfaces themselves
    edges = [RMIN] + list(RADII)
    for i in range(len(edges) - 1):
        add(f"ToyShell{i}", edges[i], edges[i + 1], "tracker:ToyLayerMat")
    add("ToyShellOut", RADII[-1], RMAX, "tracker:ToyLayerMat")
    edges = [RADII[-1]]
else:
  edges = [RMIN]
  for i, r in enumerate(RADII):
    if r > edges[-1] + 1e-6:
        add(f"ToyGap{i}", edges[-1], r, "materials:Vacuum")
    for j in range(NSUB):
        add(f"ToyLayer{i}_{j}", r + j * T / NSUB, r + (j + 1) * T / NSUB,
            "tracker:ToyLayerMat")
    edges.append(r + T)
  add("ToyGapOut", edges[-1], RMAX, "materials:Vacuum")

hdr = ('<?xml version="1.0"?>\n<DDDefinition xmlns="http://www.cern.ch/cms/DDL" '
       'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
       'xsi:schemaLocation="http://www.cern.ch/cms/DDL '
       '../../../DetectorDescription/Schema/DDLSchema.xsd">\n')
# no double hyphen anywhere in this comment: XML forbids it and it has cost two
# fatal parse errors in this project already
body = f"""
 <!-- Layer thickness {T} cm, density {RHO:.4f} g/cm3 (rho*T fixed).
      Generated by test/gen_toy_config.py; do not hand edit. -->
 <MaterialSection label="tracker.xml">
  <ElementaryMaterial name="ToyLayerMat" density="{RHO:.6f}*g/cm3" symbol=" "
                      atomicWeight="16.0*g/mole" atomicNumber="8"/>
 </MaterialSection>
 <SolidSection label="tracker.xml">
  <Polycone name="Tracker" startPhi="0*deg" deltaPhi="360*deg">
   <ZSection z="-[cms:TrackBeamZ2]" rMin="[cms:TrackBeamR2]" rMax="[cms:TrackCalorR]"/>
   <ZSection z="-[cms:TrackBeamZ1]" rMin="[cms:TrackBeamR1]" rMax="[cms:TrackCalorR]"/>
   <ZSection z="[cms:TrackBeamZ1]"  rMin="[cms:TrackBeamR1]" rMax="[cms:TrackCalorR]"/>
   <ZSection z="[cms:TrackBeamZ2]"  rMin="[cms:TrackBeamR2]" rMax="[cms:TrackCalorR]"/>
  </Polycone>
{chr(10).join(sol)}
 </SolidSection>
 <LogicalPartSection label="tracker.xml">
  <LogicalPart name="Tracker" category="unspecified">
   <rSolid name="tracker:Tracker"/>
   <rMaterial name="materials:Vacuum"/>
  </LogicalPart>
{chr(10).join(lp)}
 </LogicalPartSection>
 <RotationSection label="tracker.xml">
  <Rotation name="180D" thetaX="90*deg" phiX="180*deg" thetaY="90*deg" phiY="90*deg" thetaZ="180*deg" phiZ="0*deg"/>
  <Rotation name="R180" thetaX="90*deg" phiX="180*deg" thetaY="90*deg" phiY="-90*deg" thetaZ="0*deg" phiZ="0*deg"/>
  <Rotation name="PAA" thetaX="180*deg" phiX="0*deg" thetaY="90*deg" phiY="90*deg" thetaZ="90*deg" phiZ="0*deg"/>
 </RotationSection>
 <PosPartSection label="tracker.xml">
{chr(10).join(pos)}
 </PosPartSection>
"""
open(os.path.join(DATA, "tracker.xml"), "w").write(hdr + body + "\n</DDDefinition>\n")

# ---- planes, from the reference helix (validated: predicted 0.9043 vs sim 0.906)
pt, eta, phi0, B, q = 3.0, 0.30, 0.70, 3.8, -1.0
R = pt / (0.3 * B) * 100.0
org, nrm, uu = [], [], []
for r in RADII:
    a = math.asin(min(r / (2 * R), 1.0))
    phi = phi0 - q * a
    z = 2 * R * a * math.sinh(eta)
    org += [r * math.cos(phi), r * math.sin(phi), z]
    nrm += [math.cos(phi), math.sin(phi), 0.0]
    uu += [-math.sin(phi), math.cos(phi), 0.0]
f = lambda v: ", ".join("%.6f" % x for x in v)
open(os.path.join(HERE, "toyPlanes_pt3.py"), "w").write(
    f"# generated by gen_toy_config.py for T={T} cm; do not hand edit\n"
    f"radii = [{f(RADII)}]\norigin = [{f(org)}]\n"
    f"normal = [{f(nrm)}]\nuaxis  = [{f(uu)}]\n")

# ---- watcher radii in the sim driver
p = os.path.join(HERE, "runToyGeomCheck.py")
s = open(p).read()
import re
s = re.sub(r"radii=cms\.vdouble\([^)]*\)",
           "radii=cms.vdouble(" + ", ".join("%.4f" % r for r in RADII) + ")", s, count=1)
open(p, "w").write(s)
if HOMO:
    print(f"HOMOGENEOUS  rho={RHO} g/cm3  {len(RADII)} scoring surfaces, "
          f"no vacuum gaps, no sub-shells")
    raise SystemExit(0)
print(f"T={T} cm  NSUB={NSUB} (sub-shell {T/NSUB:.4f} cm)  rho={RHO} g/cm3  "
      f"{len(RADII)} surfaces, {len(RADII)*(NSUB+1)} material boundaries")
