#!/usr/bin/env python3
"""Regenerate tracker.xml with a given layer thickness at FIXED total material.

Total dE and X0 depend only on rho*T*N, so scanning T with rho ~ 1/T changes the
STEP STRUCTURE while leaving the integrated material alone. That isolates the
step-size dependence, which is the thing under test: the mean/median ratio is
known to be step-size dependent (0.747 per step vs 0.887 summed).

usage: python gen_toy_layers.py T_cm      (rho is derived)
"""
import sys

T = float(sys.argv[1])
RHO = 9.0 * 0.10 / T          # keep rho*T fixed at the 0.1 cm / 9.0 g/cm3 point
radii = [4.2, 7.3, 10.2, 26.9, 27.1, 35.2, 40.3, 43.2, 51.8, 61.6, 67.9, 75.0,
         85.5, 94.6, 106.8]
RMIN, RMAX, DZ = 3.15, 123.0, 194.0
if T > 0.19:
    raise SystemExit("T too large: radii 26.9/27.1 are only 0.2 cm apart")

sol, lp, pos = [], [], []
def add(name, r0, r1, mat):
    sol.append(f'  <Tubs name="{name}" rMin="{r0:.4f}*cm" rMax="{r1:.4f}*cm" '
               f'dz="{DZ}*cm" startPhi="0*deg" deltaPhi="360*deg"/>')
    lp.append(f'  <LogicalPart name="{name}" category="unspecified">\n'
              f'   <rSolid name="tracker:{name}"/>\n   <rMaterial name="{mat}"/>\n'
              f'  </LogicalPart>')
    pos.append(f'  <PosPart copyNumber="1">\n   <rParent name="tracker:Tracker"/>\n'
               f'   <rChild name="tracker:{name}"/>\n  </PosPart>')

edges = [RMIN]
for i, r in enumerate(radii):
    if r > edges[-1] + 1e-6:
        add(f"ToyGap{i}", edges[-1], r, "materials:Vacuum")
    add(f"ToyLayer{i}", r, r + T, "tracker:ToyLayerMat")
    edges.append(r + T)
add("ToyGapOut", edges[-1], RMAX, "materials:Vacuum")

hdr = ('<?xml version="1.0"?>\n<DDDefinition xmlns="http://www.cern.ch/cms/DDL" '
       'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
       'xsi:schemaLocation="http://www.cern.ch/cms/DDL '
       '../../../DetectorDescription/Schema/DDLSchema.xsd">\n')
# NOTE: no ' - - ' in this comment. XML forbids a double hyphen inside comments
# and it has now cost two fatal parse errors in this project.
body = f"""
 <!-- Thin layers with vacuum gaps. Layer thickness {T} cm, density {RHO:.4f}
      g/cm3, chosen so rho*T*N is unchanged: the integrated dE and X0 stay
      fixed while the step structure varies. Generated by gen_toy_layers.py. -->
 <MaterialSection label="tracker.xml">
  <ElementaryMaterial name="ToyLayerMat" density="{RHO:.6f}*g/cm3" symbol=" "
                      atomicWeight="16.0*g/mole" atomicNumber="8"/>
 </MaterialSection>
 <SolidSection label="tracker.xml">
  <Polycone name="Tracker" startPhi="0*deg" deltaPhi="360*deg">
   <ZSection z="-[cms:TrackBeamZ2]" rMin="[cms:TrackBeamR2]" rMax="[cms:TrackCalorR]"/>
   <ZSection z="-[cms:TrackBeamZ1]" rMin="[cms:TrackBeamR1]" rMax="[cms:TrackCalorR]"/>
   <ZSection z="[cms:TrackBeamZ1]"  rMin="[cms:TrackBeamR1]" rMax="[cms:TrackCalorR]"/>
   <ZSection z="[cms:TrackBeamZ2]"  rMin="[cms:TrackBeamR2]" rMax="[cms:TrackCalorR]"/>
  </Polycone>
{chr(10).join(sol)}
 </SolidSection>
 <LogicalPartSection label="tracker.xml">
  <LogicalPart name="Tracker" category="unspecified">
   <rSolid name="tracker:Tracker"/>
   <rMaterial name="materials:Vacuum"/>
  </LogicalPart>
{chr(10).join(lp)}
 </LogicalPartSection>
 <RotationSection label="tracker.xml">
  <Rotation name="180D" thetaX="90*deg" phiX="180*deg" thetaY="90*deg" phiY="90*deg" thetaZ="180*deg" phiZ="0*deg"/>
  <Rotation name="R180" thetaX="90*deg" phiX="180*deg" thetaY="90*deg" phiY="-90*deg" thetaZ="0*deg" phiZ="0*deg"/>
  <Rotation name="PAA" thetaX="180*deg" phiX="0*deg" thetaY="90*deg" phiY="90*deg" thetaZ="90*deg" phiZ="0*deg"/>
 </RotationSection>
 <PosPartSection label="tracker.xml">
{chr(10).join(pos)}
 </PosPartSection>
"""
open("tracker.xml", "w").write(hdr + body + "\n</DDDefinition>\n")
print(f"T={T} cm  rho={RHO:.4f} g/cm3  ({len(radii)} layers, rho*T fixed)")
